defaults:
  - _self_
  - runner: train_gen

exp:
  project: mus_unlearning_${runner.tags[0]}
  uuid: ${now:%m%d_%H%M%S}@${exp.cmt}
  cmt: null_comment
  save_dir: ${hydra:runtime.cwd}/logs/${exp.uuid}
  seed: 0
  resume_from: ${oc.env:RESUME_FROM,null}

wandb:
  entity: ${oc.env:WANDB_ENTITY,null}
  mode: ${oc.env:WANDB_MODE,online}
  run_id: ${oc.env:WANDB_RUN_ID,null}
  log_model: false

hydra:
  run:
    dir: ${exp.save_dir}/hydra_output
